<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { ArrowRight, Check, CreditCard, PackageOpen, ShieldCheck } from 'lucide-vue-next'
import SiteHeader from './SiteHeader.vue'; import SiteFooter from './SiteFooter.vue'; import { supabase,useAuth } from './auth'; import { orderPath } from './routes'; import { preloadMarkdown,renderMarkdown } from './markdown'
const auth=useAuth();const products=ref<any[]>([]);const providers=ref<any[]>([]);const selectedProvider=ref('');const busy=ref('');const message=ref('');const pendingOrder=ref<any>(null)
watch(()=>auth.ready.value,ready=>{if(ready&&!auth.user.value)auth.requireUser('/buy')},{immediate:true})
onMounted(async()=>{void preloadMarkdown();if(!supabase)return;const [{data:p},{data:ways}]=await Promise.all([supabase.from('artifacts').select('*').eq('active',true).order('price_minor'),supabase.from('payment_providers').select('id,display_name,public_config').eq('enabled',true).order('sort_order')]);products.value=p??[];providers.value=ways??[];selectedProvider.value=providers.value[0]?.id??''})
const money=(p:any)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:p.currency}).format(p.price_minor/100)
async function buy(product:any){if(!auth.session.value)return;busy.value=product.id;message.value='';pendingOrder.value=null;const r=await fetch('/api/checkout',{method:'POST',headers:{Authorization:`Bearer ${auth.session.value.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({artifact_id:product.id,provider:selectedProvider.value})});const data=await r.json();busy.value='';if(!r.ok){message.value=data.error;
// A 409 means an existing pending order is in the way. Sending the buyer to it beats a dead end —
// that page is where they either finish paying or cancel.
pendingOrder.value=data.pending_order??null;return}location.href=data.order.checkout_url||orderPath(data.order.id)}
</script>
<template><div class="fluent-page"><SiteHeader/><main class="commerce-main"><section class="commerce-hero"><p class="eyebrow">AETHERAC ARTIFACTS</p><h1>选择适合你网络规模的构建。</h1><p>价格和 SKU 由管理员实时配置。每次购买都会生成归属于当前账户的订单。</p></section><section class="payment-choice"><span>支付方式</span><select v-model="selectedProvider"><option v-for="p in providers" :key="p.id" :value="p.id">{{p.display_name}}</option></select><small v-if="!providers.length">当前没有启用的支付平台</small></section><section class="product-grid"><article v-for="(p,index) in products" :key="p.id" :class="{featured:index===1}"><div class="product-icon"><PackageOpen/></div><span>{{p.sku}}</span><h2>{{p.name}}</h2><div class="product-desc markdown-body" v-html="renderMarkdown(p.description)"></div><strong>{{money(p)}}</strong><ul><li v-for="feature in (p.metadata?.features||['绑定 AetherAC 账户','订单与退款记录','安全支付回调'])" :key="feature"><Check :size="16"/>{{feature}}</li></ul><button :disabled="!selectedProvider||busy===p.id" @click="buy(p)">{{busy===p.id?'创建订单…':'立即购买'}}<ArrowRight :size="17"/></button></article><div v-if="!products.length" class="fluent-empty"><ShieldCheck/><h2>商品正在准备中</h2><p>管理员可在 /admin 配置 Artifact SKU、价格与币种。</p></div></section><p class="form-message">{{message}}</p><p v-if="pendingOrder" class="form-message"><a class="fluent-primary" :href="orderPath(pendingOrder.id)">前往待支付订单 {{pendingOrder.sku}} <ArrowRight :size="16"/></a></p></main><SiteFooter/></div></template>
