<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { createClient, type SupabaseClient, type User } from '@supabase/supabase-js'
import { Github, LogIn, LogOut, Settings2, Users, FileText, Plus, Save, Trash2 } from 'lucide-vue-next'
import SiteHeader from './SiteHeader.vue'
import SiteFooter from './SiteFooter.vue'
const url=import.meta.env.VITE_SUPABASE_URL as string|undefined
const key=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined
const configured=computed(()=>Boolean(url&&key)); const client=ref<SupabaseClient|null>(null); const user=ref<User|null>(null)
const email=ref(''); const password=ref(''); const message=ref(''); const group=ref('default'); const mode=ref<'password'|'magic'>('password')
const tab=ref<'posts'|'progress'|'repositories'|'settings'|'users'>('posts'); const items=ref<any[]>([]); const editing=ref<any>(null)
const canRead=computed(()=>['read','coworker','admin'].includes(group.value)); const canEdit=computed(()=>['coworker','admin'].includes(group.value)); const isAdmin=computed(()=>group.value==='admin')
onMounted(async()=>{if(!configured.value)return; client.value=createClient(url!,key!); const {data}=await client.value.auth.getUser(); user.value=data.user; client.value.auth.onAuthStateChange(async(_e,s)=>{user.value=s?.user??null;if(user.value)await loadGroup()});if(user.value){await loadGroup();await loadItems()}})
async function login(){if(!client.value)return;const r=mode.value==='magic'?await client.value.auth.signInWithOtp({email:email.value,options:{emailRedirectTo:location.href}}):await client.value.auth.signInWithPassword({email:email.value,password:password.value});message.value=r.error?.message??'登录成功';if(!r.error&&mode.value==='password'){await loadGroup();await loadItems()}}
async function loadGroup(){const {data}=await client.value!.from('user_profiles').select('group_name').eq('user_id',user.value!.id).maybeSingle();group.value=data?.group_name??'default'}
async function logout(){await client.value?.auth.signOut();user.value=null;group.value='default';items.value=[]}
async function loadItems(){if(!client.value||!canRead.value)return;const table=tab.value==='posts'?'posts':tab.value==='progress'?'progress_entries':tab.value==='repositories'?'repositories':tab.value==='users'?'user_profiles':'site_settings';const {data,error}=await client.value.from(table).select('*');message.value=error?.message??'';items.value=data??[]}
function createItem(){if(!canEdit.value)return;editing.value=tab.value==='posts'?{kind:'news',title:'',slug:'',summary:'',body:'',tags:[],status:'draft'}:tab.value==='progress'?{stage:'00',title:'',summary:'',percent:0,status:'planned',sort_order:items.value.length}:tab.value==='repositories'?{name:'',label:'',enabled:true}:tab.value==='settings'?{id:true,supabase_url:'',supabase_anon_key:'',github_api_key:''}:null}
async function saveItem(){if(!client.value||!editing.value||(!canEdit.value&&!isAdmin.value))return;const table=tab.value==='posts'?'posts':tab.value==='progress'?'progress_entries':tab.value==='repositories'?'repositories':tab.value==='settings'?'site_settings':'user_profiles';const p={...editing.value};if(typeof p.tags==='string')p.tags=p.tags.split(',').map((x:string)=>x.trim()).filter(Boolean);const {error}=await client.value.from(table).upsert(p);message.value=error?.message??'已保存';if(!error){editing.value=null;await loadItems()}}
async function removeItem(i:any){if(!client.value||!canEdit.value||!confirm('确认删除？'))return;const t=tab.value==='posts'?'posts':tab.value==='progress'?'progress_entries':'repositories';await client.value.from(t).delete().eq('id',i.id);await loadItems()}
async function switchTab(v:any){tab.value=v;editing.value=null;await loadItems()}
</script>
<template><div class="dark-page studio-page"><SiteHeader/><main class="content-main"><section class="subpage-hero studio-hero"><div class="content-container"><div class="kicker"><Settings2 :size="14"/> CONTENT OPERATIONS</div><h1>Aether Studio</h1><p>统一管理内容、Supabase、GitHub、多仓库与用户组。</p></div></section><section class="studio-shell content-container"><div v-if="!configured" class="studio-state"><h2>CMS 尚未配置</h2></div><div v-else-if="!user" class="studio-login"><LogIn :size="28"/><h2>登录 Studio</h2><p>支持账户密码或 GitHub OAuth 登录。</p><input v-model="email" type="email" placeholder="邮箱"><input v-if="mode==='password'" v-model="password" type="password" placeholder="密码"><div><button @click="login">{{mode==='password'?'登录':'发送登录链接'}}</button><button @click="mode=mode==='password'?'magic':'password'">{{mode==='password'?'使用邮箱链接':'使用密码登录'}}</button><button @click="client?.auth.signInWithOAuth({provider:'github',options:{redirectTo:location.href}})"><Github :size="15"/> GitHub</button></div><span>{{message}}</span></div><div v-else-if="!canRead" class="studio-state"><h2>您的用户组无权访问此页面</h2><p>当前用户组：{{group}}</p></div><template v-else><div class="studio-toolbar"><div class="studio-tabs"><button :class="{active:tab==='posts'}" @click="switchTab('posts')"><FileText :size="15"/> Blog / News</button><button :class="{active:tab==='progress'}" @click="switchTab('progress')">进度</button><button v-if="isAdmin" @click="switchTab('repositories')">仓库</button><button v-if="isAdmin" @click="switchTab('settings')">设置</button><button v-if="isAdmin" @click="switchTab('users')"><Users :size="15"/> 用户组</button></div><div>{{user.email}} · {{group}} <button @click="logout"><LogOut :size="16"/></button></div></div><div class="studio-grid"><div class="studio-list"><div class="studio-list-head"><span>{{tab.toUpperCase()}}</span><button v-if="canEdit&&tab!=='settings'&&tab!=='users'" @click="createItem"><Plus :size="15"/> 新建</button></div><article v-for="i in items" :key="i.id" @click="canEdit&&(editing={...i,tags:i.tags?.join(', ')})"><div><span>{{i.kind||i.name||i.stage||i.user_id}}</span><h3>{{i.title||i.label||i.group_name||i.name}}</h3></div><button v-if="canEdit&&tab!=='settings'&&tab!=='users'" @click.stop="removeItem(i)"><Trash2 :size="14"/></button></article></div><form v-if="editing" class="studio-editor" @submit.prevent="saveItem"><h2>编辑</h2><label v-for="(_,k) in editing" :key="k">{{k}}<input v-model="editing[k]"></label><button class="save-button" type="submit"><Save :size="15"/> 保存</button></form><div v-else class="studio-placeholder">选择项目查看详情。</div></div></template></section></main><SiteFooter/></div></template>
